language: node_js 
node_js:
  - 14
cache:
  directories:
  - node_modules 
script:
  - npm run build 
  - npm run github
deploy:
  provider: pages 
  skip_cleanup: true 
  github_token: $github_token 
  local_dir: out
  target_branch: ecea
  repo: Purdue-ECESS/website
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(main)$


